I added unit test, package management and CI integration
oplog/dynamic-query-builder-client pull request #4
Opened 2018-09-30 08:29 UTC by emrekeskinmac

2018-10-02 14:53 UTC, aacanakin reviewed
Hi @emrekeskinmac,
Thanks for your great contribution.
Currently, we are using jest internally but that's ok for now because there were no open source tests before your contribution.
I have added small change requests for your pull request.
I'll provide circle ci account here as soon as possible. Ping @ardadevelioglu

2018-10-02 14:53 UTC, aacanakin commented on src/test/BooleanFilter.ts
> +import { BooleanFilter, BooleanFilterOperation } from '..';
Can you modify this import to the following for faster test loading?
```ts
import { BooleanFilter, BooleanFilterOperation } from '../BooleanFilter';
```

2018-10-02 14:53 UTC, aacanakin commented on src/test/DateFilter.ts
> +import { DateFilter, DateFilterOperation } from '..';
Can you modify this import to the following for faster test loading?
```ts
import { DateFilter, DateFilterOperation } from '../DateFilter';
```

2018-10-02 14:53 UTC, aacanakin commented on src/test/NumericFilter.ts
> +import { NumericFilter, NumericFilterOperation } from '..';
Can you modify this import to the following for faster test loading?
```ts
import { NumericFilter, NumericFilterOperation } from '../NumericFilter';
```

2018-10-02 14:53 UTC, aacanakin commented on src/test/Pagination.ts
> +import { Pagination } from '..';
Can you modify this import to the following for faster test loading?
```ts
import { Pagination } from '../Pagination';
```

2018-10-02 14:53 UTC, aacanakin commented on src/test/StringBuilder.ts
> +import { StringFilter, StringFilterOperation } from '..';
Can you modify this import to the following for faster test loading?
```ts
import { StringFilter, StringFilterOperation } from '../StringFilter';
```

2018-10-02 14:53 UTC, aacanakin commented on tsconfig.json
> +    "outDir": "./lib"
For conventions, can you change `"outDir": "./dist"`?

2018-10-02 14:53 UTC, aacanakin commented on README.md
> +[![CircleCI](https://circleci.com/gh/emrekeskinmac/dynamic-query-builder-client/tree/feature%2Funit-tests.svg?style=svg)](https://circleci.com/gh/emrekeskinmac/dynamic-query-builder-client/tree/featu
I'll provide here oplog account for circle ci as soon as possible

2018-10-02 22:02 UTC, emrekeskinmac commented
Hi @aacanakin 
Thank you for accepting PR. Great progress for me. 
I'm editing my mistakes and waiting for CircleCI account.

Thank you so much @aacanakin  @ardadevelioglu

2018-10-03 06:45 UTC, aacanakin requested changes

2018-10-03 06:45 UTC, aacanakin commented on README.md
> +[![CircleCI](https://circleci.com/gh/emrekeskinmac/dynamic-query-builder-client/tree/feature%2Funit-tests.svg?style=svg)](https://circleci.com/gh/emrekeskinmac/dynamic-query-builder-client/tree/featu
We have created circle ci account for oplog. Can you change status badge to the following;
```
[![CircleCI](https://circleci.com/gh/oplog/dynamic-query-builder-client.svg?style=svg)](https://circleci.com/gh/oplog/dynamic-query-builder-client)
```

2018-10-03 07:00 UTC, emrekeskinmac commented
@aacanakin I have edited CircleCI status badge.

2018-10-03 07:19 UTC, aacanakin commented
@emrekeskinmac Thanks

2018-10-03 07:22 UTC, aacanakin approved these changes

2018-10-03 07:22 UTC, merged